add nano g1
meshtastic/Meshtastic-device pull request #1351
Opened 2022-04-02 20:06 UTC by neilhao

Meshtastic Mesh Device Nano Edition G1 has been added. The code could be compiled successfully. 
This is my first commit to Meshtastic, hope I didn't get anything wrong.

Neil

2022-04-02 20:16 UTC, caveman99 requested changes
Pretty good for a firest PR. Please review my comments, other than that it's good to go.

2022-04-02 20:16 UTC, caveman99 commented on platformio.ini
>  ;default_envs = meshtastic-diy-v1
Please don't edit the master platformio.ini unless absolutely necessary. This change can be reverted without harm.

2022-04-02 20:16 UTC, caveman99 commented on src/configuration.h
Please revert that change, the type of controller (1106/1306) is auto-detected now if it is present on the i2c bus. see https://github.com/meshtastic/Meshtastic-device/blob/a8ef3967cde22993608c7adba051b3cea502ba30/src/debug/i2cScan.h#L6-L25

2022-04-02 20:32 UTC, caveman99 approved these changes

2022-04-02 20:47 UTC, caveman99 commented
Caveat: If this is approved, the protobufs in master need to be updated before it is merged.

2022-04-03 22:01 UTC, sachaw requested changes
Looks great, just some line cleanup, then we can squash and merge.

2022-04-03 23:43 UTC, mc-hamster commented
This really is beautiful. Way to go!

2022-04-04 10:16 UTC, merged