Powers off eink backlights before shutdown
meshtastic/Meshtastic-device pull request #1867
Opened 2022-10-27 18:05 UTC by t413

- t-echo boards in particular need this
- follows the existing defines structure for backlight control

thanks!

2022-10-27 18:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/meshtastic/Meshtastic-device?pullRequest=1867) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/meshtastic/Meshtastic-device?pullRequest=1867) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/meshtastic/Meshtastic-device?pullRequest=1867) it.</sub>

2022-10-27 19:04 UTC, t413 commented
Tested on-device and it works as expected. Backlight tuns off when shut down.

2022-10-27 19:44 UTC, caveman99 requested changes

2022-10-27 19:44 UTC, caveman99 commented on src/Power.cpp
> +#endif
Can you please add an additional macro guard to make sure PIN_EINK_EN is defined before you use it? Asking for a hypothetical new device with EINK but without that PIN Definition.

2022-10-28 01:03 UTC, t413 commented
Also addressed the same #define guard in src/ButtonThread.h:162 since that's what I based it on.

2022-10-28 09:22 UTC, caveman99 approved these changes

2022-10-28 09:23 UTC, merged