Use SD card as store&forward memory
meshtastic/Meshtastic-device pull request #5083
Opened 2024-10-16 19:12 UTC by caveman99

Not 100% sure if this is a good idea.

2024-10-16 19:12 UTC, caveman99 commented
n.b. this enables store&forward as a client for non-esp32 devices.

2024-10-16 20:11 UTC, caveman99 commented
@markbirss yes, I wanna go slowly step by step. For the rak I thought the flash add-ons would be a better choice. Still looking into this.

2024-10-16 20:31 UTC, GUVWAF commented
Sounds really nice.

Any idea on how long a write and read takes (since it seems this isn't asynchronous)?

2024-10-16 20:41 UTC, caveman99 commented
> Any idea on how long a write and read takes (since it seems this isn't asynchronous)?

Nope, i couldn't test it (yet). It's 200ish byte per file, but also the SDcard interface is usually single lane.

2025-02-22 13:46 UTC, GUVWAF commented
Please see #6121: currently this causes the radio to be not detected, so the reorganization of the SPI definitions when using an SD card has to be revisited.

2025-02-23 01:11 UTC, Woutvstk commented
> Please see #6121: currently this causes the radio to be not detected, so the reorganization of the SPI definitions when using an SD card has to be revisited.

-> Should be fixed with #6126

2025-02-23 17:53 UTC, Woutvstk commented
Since f7feea6, I've been having trouble at runtime on rak4631 in de S&F branch. There is some critical error during initialisation. Something to do with an SPI lock.

```
//\ E S H T /\ S T / C

DEBUG | ??:??:?? 2 Filesystem files:
DEBUG | ??:??:?? 2    RAK (108 Bytes)
DEBUG | ??:??:?? 2  adafruit (directory)
DEBUG | ??:??:?? 2  bond_prph (directory)
DEBUG | ??:??:?? 2  bond_cntr (directory)
DEBUG | ??:??:?? 2  prefs (directory)
DEBUG | ??:??:?? 2    channels.proto (57 Bytes)
DEBUG | ??:??:?? 2    config.proto (173 Bytes)
DEBUG | ??:??:?? 2    module.proto (109 Bytes)
DEBUG | ??:??:?? 2    db.proto (660 Bytes)
DEBUG | ??:??:?? 2 Power::lipoInit lipo sensor is not ready yet
DEBUG | ??:??:?? 2 Use analog input 5 for battery level
INFO  | ??:??:?? 2 Scan for i2c devices
DEBUG | ??:??:?? 2 Scan for I2C devices on port 1
INFO  | ??:??:?? 2 BME680 found at address 0x76
INFO  | ??:??:?? 2 1 I2C devices found
DEBUG | ??:??:?? 2 acc_info = 0
ERROR | ??:??:?? 2 assert failed src\SPILock.cpp: 10, void initSPI(), te
```

After this, no further output and the device is non responsive. Does anyone know what causes this? Thanks

2025-03-23 23:58 UTC, Woutvstk commented
I just added a pull request to this branch. The S&F functionality is working on the nRF52 now. (only tested with rak4631+rak15002). 
However, I ran into some problems:
- The scanning for free space now also works on the nrf52 platform but it takes considerable time (during boot). On the rak4631+RAK15002, it now takes about 8 seconds per GB of SD card to scan the free clusters. After that, free cluster count is maintained, at no further delays are present. This now causes the boot process to be stuck while this scanning is happening. Is this expected behaviour (is this also present on the ESP32?) and could/should this be solved? 

- Now, for every packet received, a new file is created. When doing some benchmarks with this new library, write times kept increasing with the increasing file count on the FAT filesystem. Again, is this expected behaviour or could this be a bug?
Writing a single historyStruct (~253 bytes) takes different amounts of time depending on how it is written to the SD card.
             - Appending to existing file: 11ms (not currently done)
             - Creating new file on empty (formatted) filesystem: 50-70ms
             - When 200 or so files are already present on the filesystem, creating and writing a new file takes up 150-250ms
             - If this is because of the FAT filesystem, this could be a problem when scaling
- Also, now only FAT32 is supported (exFat is not) because this reduces flash usage and should provide plenty of storage space.

2025-03-28 11:49 UTC, markbirss commented
@Woutvstk i assume the SdFormatter example should still work ? (i might want to try sdnand)
https://www.adafruit.com/product/4899

2025-03-30 14:06 UTC, Woutvstk commented
> @Woutvstk i assume the SdFormatter example should still work ? (i might want to try sdnand and might need to erase it) https://www.adafruit.com/product/4899

Not sure I'm following. The SdCardFormatter example from the SdFat library uses the SdFat library. Meshtastic now uses a wrapper of the SdFat library with another API (similar to the one from the ESP32 SD library). The format function is not included in the wrapper library (SdFatWrapper25) yet. (only functions used in meshtastic are defined for now).

2025-03-30 15:22 UTC, markbirss commented
> > @Woutvstk i assume the SdFormatter example should still work ? (i might want to try sdnand and might need to erase it) https://www.adafruit.com/product/4899
> 
> Not sure I'm following. The SdCardFormatter example from the SdFat library uses the SdFat library. Meshtastic now uses a wrapper of the SdFat library with another API (similar to the one from the ESP32 SD library). The format function is not included in the wrapper library (SdFatWrapper25) yet. (only functions used in meshtastic are defined for now).

Ok, understood, thank you

2025-04-07 13:33 UTC, thebentern approved these changes

2025-04-07 15:07 UTC, mverch67 requested changes

2025-04-07 15:21 UTC, caveman99 commented on src/mesh/NodeDB.cpp
> +// #if !MESHTASTIC_EXCLUDE_STOREFORWARD
not intentional, i will check where thatw as introduced!

2025-04-08 09:04 UTC, Woutvstk commented on variants/rak4631/variant.h
> +#define SDCARD_SPI SPI1
Yes, that is not supposed to be there anymore. I'll make a quick pr to change it and another outdated comment. (PR #6520)

2025-05-08 06:48 UTC, d4rkmen commented
I was looking deep inside this branch, and it requires next changes:

- refactor to use custom storage types. possible cases: SDCard / NVS / SPIFFS / USB drive (may be even more ways)
- move to selectable S&F storage type on build, device can have both PSRAM / SDCARD / etc
- getter/setter for node last index - important to keep indeces in non-volatile memory to keep the queue on reboots (settings changes requires reboot and loosing the queue)

I have made some changes on current (2.6.7) version locally but not sure how to contribute it right.

2025-05-24 21:45 UTC, d4rkmen commented
Consider the FATFS library used for SDCard eats 30kb of RAM, making ESP32 system unusable (api server has no free ram to serve)

2026-02-04 13:27 UTC, closed without merging